### PR TITLE
SwiftFormatPrettyPrint: update for API changes

### PR DESCRIPTION
**Pull request by compnerd**
Update for changes to `_InternalSwiftSyntaxParser` for async operations.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by allevato — COMMENTED** [review]
Thanks! (CI is failing because it's not using the correct toolchain to build swift-syntax; see https://github.com/apple/swift-format/pull/251).

I ran the tests locally with the latest development snapshot (on macOS) and hit an assertion failure:

```
$ TOOLCHAINS=org.swift.50202104261a swift test
...
Test Case '-[SwiftFormatRulesTests.ReturnVoidInsteadOfEmptyTupleTests testTriviaPreservation]' started.
Assertion failed: (isValid() && "length does not make sense for an invalid range"), function getByteLength, file /Users/buildnode/jenkins/workspace/oss-swift-package-macos/swift/include/swift/Basic/SourceLoc.h, line 218.
Exited with signal code 6
```

Do you see a similar failure on your platform?

**Comment by compnerd** [comment]
I pinged @shahmishal about the toolchain version, he said he was going to look into correcting that.

Interesting, I'll try to run the test suite again, Im running in a weird environment (different versions across different locations, so easy to mix up things).

**Comment by compnerd** [comment]
Okay, I can verify that I do see that failure on Windows as well.

**Comment by allevato** [comment]
I've filed SR-14552 and SR-14553 to address the bugs and/or behavior changes in the parser; in the meantime, I'll cycle back around in the morning and fix or disable the affected tests on `main` to unblock things.

**Comment by allevato** [comment]
Now that the 2021-05-03 developer snapshot is up, I've confirmed we're still in a good state after the recent additions to swift-syntax for `PostfixIfConfigExpr` (everything builds/tests pass, but we'll need to add support for postfix `#if` to be properly formatted later).

**Pull request merged**
