### PR TITLE
Revert generate pipeline plugin

### PR DESCRIPTION
**Pull request by DougGregor**
Revert https://github.com/apple/swift-format/pull/416 and https://github.com/apple/swift-format/pull/419 because they appear to be breaking Swift pull request testing.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@allevato this revert PR is because we think https://github.com/apple/swift-format/pull/416 and https://github.com/apple/swift-format/pull/419 are causing the silent SwiftSyntax build failures we're seeing in Swift CI. The referenced PR (https://github.com/apple/swift/pull/61545) is where we're testing out this theory.

**Comment by allevato** [comment]
@ahoppen mentioned this to me as well. Given the issue on Windows as well (#422) maybe this is the best option if we confirm that it's the problem.

Any idea why the plug-in is causing the failures?

If we had the swift-ci trigger working on this repo, would it have caught the problem before it was merged? cc @shahmishal

**Review by allevato — APPROVED** [review]
I'll go ahead and approve this just in case; feel free to merge it if your testing confirms the plugin was the problem, and let me know if there's anything I can do to help get it working again after that!

**Comment by DougGregor** [comment]
Yeah, I've confirmed that the plug-in was the problem, so I'm going to go ahead and merge. Sorry about that--let's look for a path forward, because this is a nice cleanup and it's unfortunate we have to revert.

**Comment by ahoppen** [comment]
> If we had the swift-ci trigger working on this repo, would it have caught the problem before it was merged? cc @shahmishal

I think what you can do in the meantime while CI triggers are not set up for this repo, is to create a fake PR to https://github.com/apple/swift/, mention the `swift-format` PR you want to test and add `@swift-ci Please test` (or your favorite test invocation). I am often doing this in https://github.com/apple/swift/pull/37710.

**Pull request merged**
