### PR TITLE
Update to Swift 5.2 release.

### PR DESCRIPTION
**Pull request by allevato**

### CODE REVIEW

**Comment by allevato** [comment]
cc @dylansturg

**Comment by BORN2LOSE** [comment]
Can I build a project right now without merging the branch?

**Comment by allevato** [comment]
> Can I build a project right now without merging the branch?

If you check this PR out locally, yes, it should build successfully with Xcode 11.4.

**Comment by evgzor** [comment]
I tried to build from https://github.com/allevato/swift-format.git and still getting 
 SwiftSyntax parser library isn't compatible

**Pull request merged**
